// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fivsmxfiokloigqqliva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdnNteGZpb2tsb2lncXFsaXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjYxNjAsImV4cCI6MjA2NTEwMjE2MH0.L7MdfQZK5PSVzLh4vUjkqP2WLRgHEdgvlZKCK5nciKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);